version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - .:/project
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
