# Generated by Django 5.0.3 on 2024-03-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('criteria_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('edit_time', models.DateTimeField(blank=True, null=True)),
                ('editor', models.CharField(blank=True, max_length=50, null=True)),
                ('create_time', models.DateTimeField()),
                ('creator', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'criteria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CriterionResponse',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'criterion_response',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Divisions',
            fields=[
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'divisions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nominations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('division_management_company', models.CharField(max_length=50)),
                ('edit_time', models.DateTimeField(blank=True, null=True)),
                ('editor', models.CharField(blank=True, max_length=50, null=True)),
                ('create_time', models.DateTimeField()),
                ('creator', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'nominations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NominationTypes',
            fields=[
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'nomination_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nominees',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('patronymic', models.CharField(blank=True, max_length=30, null=True)),
                ('position', models.CharField(max_length=100)),
                ('divide', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=20)),
                ('is_experience_in_atom_above_year', models.BooleanField()),
                ('no_offenses', models.BooleanField()),
                ('no_discipline_offensives', models.BooleanField()),
                ('photo', models.BinaryField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nominees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'organizations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('project_team_name', models.CharField(blank=True, max_length=100, null=True)),
                ('about_information', models.CharField(blank=True, max_length=500, null=True)),
                ('not_secret', models.BooleanField()),
                ('to_data_processing', models.BooleanField()),
                ('to_processing_other_data', models.BooleanField()),
                ('creator_is_tech_support', models.BooleanField()),
                ('new_products', models.BooleanField()),
                ('global_achievements', models.BooleanField()),
                ('market_share_increase', models.BooleanField()),
                ('сost_reduction', models.BooleanField()),
                ('core_achievement', models.CharField(max_length=1000)),
                ('consent_file', models.BinaryField(blank=True, null=True)),
                ('is_start_reconciliation', models.BooleanField()),
                ('edit_time', models.DateTimeField(blank=True, null=True)),
                ('editor', models.CharField(blank=True, max_length=100, null=True)),
                ('create_time', models.DateTimeField()),
                ('creator', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'requests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RequestsOfNominees',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'requests_of_nominees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RequestTypes',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'request_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('login', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
